### ISSUE TITLE
App bar bug of disposition of element on UI

### ISSUE THREAD

**Issue by NiccoloMenozzi** [dreamonkey/quasar#110] opened 2022-02-25 13:12 UTC
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

A bug on the dense app bar when you are on docs. The bug is there regardless of the UI version selected.
On Mac, probably Mac OS problem, in Chrome.

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

[](https://quasar.beget.it/docs)

<img width="1440" alt="Schermata 2022-02-25 alle 14 10 14" src="https://user-images.githubusercontent.com/84564560/155720722-8a098e4c-6305-4a2a-beaa-a74e8c8044fc.png">

**Comment by yusufkandemir** [comment] 2022-02-25 13:27
Happens on Windows 11, Chromium Edge 98.0.1108.50 too.

**Comment by IlCallo** [comment] 2022-02-25 15:41
This is caused by the addition of the theme switcher icon 🥲 
Fixed into #108 , had to do a lot of manual tweak unluckily

**Closed as completed by IlCallo** 2022-02-25 15:41 UTC
Labels: bug, severity-1-important
